let colores = ["azul", "amarillo"];
console.log(colores);
colores.unshift("violeta");
console.log(colores);
colores.push("verde");
console.log(colores);
colores.shift();
console.log(colores);
colores.pop();
console.log(colores);
